### ISSUE TITLE
problem running the main.py

### ISSUE THREAD

**Issue by gohguodong** [maudzung/TTNet-Real-time-Analysis-System-for-Table-Tennis-Pytorch#11]
Hi,

I tried running the code following the instruction. i got this error when trying to run the main.py. i have checked and i am sure the folders and files exist. what could be the problem? i am using windows 10.

File "C:\Users\user\Desktop\TTNet\src\data_process\ttnet_data_utils.py", line 95, in get_events_infor
    json_ball = open(ball_annos_path)
FileNotFoundError: [Errno 2] No such file or directory: '../../dataset\\training\\annotations\\game_1\\ball_markup.json'

**Comment by Razamalik4497** [comment]
how did you resolve it ? I got the same error ..

**Comment by sisrfeng** [comment]
parser.add_argument('--working-dir', type=str, default='../../', metavar='PATH',
                        help='the ROOT working directory')

change to

parser.add_argument('--working-dir', type=str, default='/data2/wf2/ttNet/', metavar='PATH',
                        help='the ROOT working directory')
