### ISSUE TITLE
AssertionError: Failed to load frame 10791

### ISSUE THREAD

**Issue by chenzhutian** [maudzung/TTNet-Real-time-Analysis-System-for-Table-Tennis-Pytorch#4]
Hi, thanks for your wonderful work.
During running the `./demo.sh`, it shows me this error
![image](https://user-images.githubusercontent.com/3315274/85979523-3edc6e80-ba13-11ea-91c4-19b1f15f2116.png)

Is it the video is broken? How can I fix it?

**Comment by MianWaleed-hub** [comment]
Hi, I am just working on ttnet and i am stuck on this same error , if you could help me to resolve this issue , really appreciate on this. Thanks
