### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [maudzung/TTNet-Real-time-Analysis-System-for-Table-Tennis-Pytorch#7]
Hey, I used the training command in `./train_1st_phase.sh` with only one main change (removed the distributed training arguments since I have just 1 GPU). The training runs fine for 1 epoch but gets stuck during the test stage forever. (Testing stage since the total batches per epoch is 118)

![Screenshot from 2020-07-26 14-41-19](https://user-images.githubusercontent.com/51472801/88475562-b936da80-cf4e-11ea-92a2-1a420596837e.png)

**Comment by maudzung** [comment]
Hi @Ashwin-Ramesh2607 
Did you solve the problem? I'll check it soon. Thanks for reporting the bug, although I have tested carefully the source code.
